### ISSUE TITLE
猜群友有时候会莫名卡住，出现报错信息

### ISSUE THREAD

**Issue by Jacky117** [BeiYazi0/groupguess#2]
以下是报错信息，发送猜群友后有时候可以获取头像有回复消息，但有时候又没有回复
![报错信息](https://user-images.githubusercontent.com/107171157/196678121-91b40319-3447-42e8-86c4-d98767ca6089.png)

**Comment by BeiYazi0** [comment]
从报错来看，好像是图片本身的问题，图片的宽小于裁剪宽度PATCH_SIZE，导致randint的第二个参数小于0，因此报错。
可能的解决办法是在
`img = Image.open(io.BytesIO(content)) `
后加上resize，调整原图的大小后再裁剪，即
`img = Image.open(io.BytesIO(content))`
`img = img.resize((W_SIZE, H_SIZE))`

**Comment by Jacky117** [comment]
再问下W_SIZE和H_SIZE一般设置成多少比较合适呢

**Comment by Jacky117** [comment]
我目前设定在了1500左右，发现还能接受，总之还是谢谢了~
